name: Update Jira Status

on:
  workflow_call:
    inputs:
      jira_auth:
        required: true
        type: string

jobs:
  action-jira-status-update:
    runs-on: ubuntu-latest

    steps:
      - name: Extract Jira Ticket IDs
        id: get-jira
        run: |
          title="${{ github.event.pull_request.title }}"
          body="${{ github.event.pull_request.body }}"
          > tickets.txt
          echo "$title" | grep -oE '[A-Z]+-[0-9]+' >> tickets.txt || true
          echo "$body" | grep -iE '^Fixes[[:space:]]*:[[:space:]]*[A-Z]+-[0-9]+' | grep -oE '[A-Z]+-[0-9]+' >> tickets.txt || true
          sort -u tickets.txt > unique_tickets.txt
          if [[ ! -s unique_tickets.txt ]]; then
            echo "ticket-ids=" >> $GITHUB_OUTPUT
            exit 0
          fi
          tickets_csv=$(paste -sd, unique_tickets.txt)
          echo "ticket-ids=$tickets_csv" >> $GITHUB_OUTPUT

      - name: Transition Jira Tickets to 'In Progress'
        if: steps.get-jira.outputs.ticket-ids != ''
        env:
          JIRA_AUTH: ${{ inputs.jira_auth }}
        run: |
          IFS=',' read -ra tickets <<< "${{ steps.get-jira.outputs.ticket-ids }}"
          for ticket_id in "${tickets[@]}"; do
            curl --fail -X POST \
              --url "https://scylladb.atlassian.net/rest/api/3/issue/${ticket_id}/transitions" \
              --user "$JIRA_AUTH" \
              --header "Accept: application/json" \
              --header "Content-Type: application/json" \
              -d '{"transition": {"id": "111"}}'
