name: Update Status - Ready For Merge

on:
  workflow_call:
    inputs:
      label_name:
        required: true
        type: string
    secrets:
      jira_auth:
        required: true

jobs:
  action-jira-status-update-ready-for-merge:
    if: ${{ github.event.label.name == inputs.label_name }}
    runs-on: ubuntu-latest

    steps:
      - name: Extract Jira Ticket IDs
        id: get-jira
        run: |
          echo "Label '${{ inputs.label_name }}' detected. Looking for Jira ticket IDs..."

          title="${{ github.event.pull_request.title }}"
          body="${{ github.event.pull_request.body }}"
          body="${body:-}"  # default to empty if null

          > tickets.txt

          echo "$title" | grep -oE '[A-Z]+-[0-9]+' >> tickets.txt || true
          echo "$body" | grep -iE '^Fixes[[:space:]]*:[[:space:]]*[A-Z]+-[0-9]+' | \
          grep -oE '[A-Z]+-[0-9]+' >> tickets.txt || true

          sort -u tickets.txt > unique_tickets.txt

          if [[ ! -s unique_tickets.txt ]]; then
            echo "No Jira tickets found in PR title or body. Skipping Jira update."
            echo "ticket-ids=" >> $GITHUB_OUTPUT
            exit 0
          fi

          tickets_csv=$(paste -sd, unique_tickets.txt)
          echo "ticket-ids=$tickets_csv" >> $GITHUB_OUTPUT

      - name: Transition Jira Tickets to 'Ready for Merge'
        if: steps.get-jira.outputs.ticket-ids != ''
        env:
          JIRA_AUTH: ${{ secrets.jira_auth }}
        run: |
          IFS=',' read -ra tickets <<< "${{ steps.get-jira.outputs.ticket-ids }}"
          for ticket_id in "${tickets[@]}"; do
            echo "Transitioning Jira ticket to 'Ready for Merge': $ticket_id"
            curl --fail -X POST \
              --url "https://scylladb.atlassian.net/rest/api/3/issue/${ticket_id}/transitions" \
              --user "$JIRA_AUTH" \
              --header "Accept: application/json" \
              --header "Content-Type: application/json" \
              -d '{"transition": {"id": "131"}}'
